[template]
keys        = [ "/services" ]
mode        = "0644"
src	        = "haproxy.cfg.tmpl"
dest	      = "/etc/haproxy/haproxy.cfg"
reload_cmd  = "haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -d -D -sf $(cat /var/run/haproxy.pid)"
